### ISSUE TITLE
Remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#1234]
**Describe the bug**
The backend is crashing (in Staging) with a hard to read error message.

**To Reproduce**
1. Restart the backend
2. Try schedule a mission with one of the robots
3. The backend fails eventually with:

Unhandled exception. Npgsql.PostgresException (0x80004005): 53300: remaining connection slots are reserved for non-replication superuser connections

**Expected behavior**
Run as normal

**Screenshots**

**Comment by aestene** [comment]
This is due to the amount of connection slots on the postgresql server we are using. We can increase the number of connection slots and we should see an improvement provided that we don't have a bug in the code which is creating an "infinite" number og connections. We have previously done this for the dev environment.

**Comment by aestene** [comment]
I have increased the connection slots to 1700 for now. Will see if it resolves the issue.

**Comment by aestene** [comment]
For reference, there were about 10 additional robots added to the staging environment which coincided with this bug coming forward so it may be that we simply need to scale our database a little for handling more robots.

**Comment by aestene** [comment]
It looks like the problem has resolved itself by upgrading the number of connection slots for now so I will close this issue.
