### ISSUE TITLE
The frontend should receive a warning the robot could not be returned home

### ISSUE THREAD

**Issue by Afonso-2403** [equinor/flotilla#1291]
**Describe the new feature you would like to see**
When the scheduling of a return home mission fails in [`OnRobotAvailable`](https://github.com/equinor/flotilla/blob/23b00904d746a51691b5b44f662af1b5cb48389c/backend/api/EventHandlers/MissionEventHandler.cs#L109), a notification should be sent to the frontend so that an appropriate message can be shown to the user.
Currently we silently fail which might lead the user to believe that the robot is in its home.

**Describe the solution you'd like**
A signalR topic?

**How will this feature affect the current Threat Model?**
This will make the system more robust given that the user will be warned if a return to home mission could not be scheduled and the robot should be physically handled.

**Comment by andchiind** [comment]
We could potentially have a generic signalR topic for alerts which sends a "FailureAlert" object containing a descriptive message as well as an alert name. We could then trigger frontend event handlers based on these alert names if more actions besides displaying the alert is needed.

**Comment by andchiind** [comment]
We may also want to consider what the robot state should be at this point. I suppose they would become Available?

**Comment by andchiind** [comment]
I think it should be up to the backend to update the robot state, so that the backend is consistent with the frontend. Currently the backend state becomes inconsistent I think, since the mission queue may remain frozen even after a failure. I think the safezone status of the robot should either be represented in the robot status, where we could also have an "inconsistent" or "needs help" status, or we need to expand the IsMissionQueueFrozen value to be more informative.
