### ISSUE TITLE
Error message displayed to the user is not logged in the backend

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#1447]
**Describe the bug**
We got `Failed to start: 'Could not reach ISAR at http://localhost:3000'` popup in the frontend, but could not find a similar log in the backend pod.

**To Reproduce**
1. Trigger some failure
2. Verify that the frontend gives a error message in a banner
3. See that no error is logged in the backend

**Expected behavior**
The backend component should also log an error if an error is displayed in the frontend.

**Screenshots**

**Comment by andchiind** [comment]
Hmm, our logger setup might have an issue then, since it should be getting logged in two places at least:

![Image](https://github.com/equinor/flotilla/assets/20266900/a1bbdf9f-3b8b-4d5f-b44f-b7c81ee5b5cf)

![Image](https://github.com/equinor/flotilla/assets/20266900/63d07633-b0fd-441f-a791-54895892ece1)

**Comment by Christdej** [comment]
Need to send frontend logs to app insights

**Comment by andchiind** [comment]
Could not be recreated, logs seemed to work fine.

**Comment by andchiind** [comment]
Could not be recreated, logs seemed to work fine.
