### ISSUE TITLE
Robot status changed on ISAR during connection loss is not updated to flotilla

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#1485]

**Comment by andchiind** [comment]
If this is refering to frontend not updating then it is caused by the way we check the new Robot value after updating it.


![Image](https://github.com/equinor/flotilla/assets/20266900/e70e48fd-a9bb-4649-9093-cc94c3a209b9)

Basically, when we fetch the new robot value after updating it, it does not yet have the new status. The value sent to SignalR is therefore also outdated.

**Comment by tsundvoll** [comment]
This is related to whether we should latch messages or some other solution. Can Event Sourcing fix this?

**Comment by oysand** [comment]
Addressed in https://github.com/equinor/isar/pull/555
