### ISSUE TITLE
Make battery and pressure status grey when robot is offline

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#912]
**Describe the improvement you would like to see**
A suggestion to make it visible that the values are not live.

**How will this change existing functionality?**
A clear and concise description on how this will affect current functionality.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by UsamaEquinorAFK** [comment]
Is it compliant with the design we have in Miro ?

**Comment by UsamaEquinorAFK** [comment]
@mariannewiggen

**Comment by mariannewiggen** [comment]
I think it makes sense to do this if the status of the robot is offline. If the status of the robot is not offline, then I don't think it is clear enough that battery and pressure change color due to values not being live.

Link to suggestion for grey battery and pressure status in Figma: https://www.figma.com/file/q6vsNRogzV6r9vTCCDsocd/Robot-Missions?type=design&node-id=4611%3A594648&mode=design&t=CSQq7Htipx2CzkLf-1

![Image](https://github.com/equinor/flotilla/assets/112481380/6f50ff78-2932-4620-ace0-ca1d272d6446)

**Comment by mariannewiggen** [comment]
Another suggestion could be to not show the value of battery and pressure if there is a high probability that the values will be wrong


![Image](https://github.com/equinor/flotilla/assets/112481380/70f4611c-39e1-4f56-8db3-ec9c5f20439c)

**Comment by UsamaEquinorAFK** [comment]
I prefer the second option. Thanks :)

**Comment by UsamaEquinorAFK** [comment]
#930
